#!/bin/sh

bold=$(tput bold)
normal=$(tput sgr0)
config_variable=$1
shift
apps=("$@")

function find_config_value {
  value="$(heroku config -a $1 | grep $2 | sed "s/$2:[[:blank:]]*//")"
  if [[ "$value" != "" ]]; then
    printf "\033[1;32m✔\033[0m ${bold}$1${normal}: $value\n"
  else
    printf "\033[1;31m✘\033[0m ${bold}$1${normal}: Not found\n"
  fi
}

if [ ! "$config_variable" ];then
  echo "Must specify a config variable."
  exit 1
fi
if [ ${#apps[@]} -eq 0 ]; then
  echo "Must specify at least one app."
  exit 1
fi

echo "\nChecking heroku authentication status..."
heroku auth:whoami

echo "\nSearching for ${bold}$config_variable${normal}..."

for app in "${apps[@]}"; do
  find_config_value $app $config_variable
done
