#!/bin/sh

bold=$(tput bold)
normal=$(tput sgr0)
config_variable=$1
shift
apps=("$@")

function find_config_value {
  value="$(heroku config -a $1 | grep "^$2:" | sed "s/$2:[[:blank:]]*//")"
  indicator="\033[1;32m✔\033[0m"
  if [[ "$value" = "" ]]; then
    indicator="\033[1;31m✘\033[0m"
    value="Not found"
  fi
  printf "$indicator ${bold}$1${normal}: $value\n"
}

function print_error_and_exit {
  echo $1
  echo "\nUsage:"
  echo "heroku-config-query CONFIG_VAR my-app-1 my-app-2"
  exit 1
}

if [ ! "$config_variable" ];then
  print_error_and_exit "Must specify a config variable."
fi
if [ ${#apps[@]} -eq 0 ]; then
  print_error_and_exit "Must specify at least one app."
fi

echo "\nChecking heroku authentication status..."
heroku auth:whoami

echo "\nSearching for ${bold}$config_variable${normal}..."

for app in "${apps[@]}"; do
  find_config_value $app $config_variable
done
